import { Suspense, useRef, useState } from "react";
import { Canvas } from "@react-three/fiber";
import {
  useGLTF,
  OrbitControls,
  RoundedBox,
  Plane,
  Sphere,
  Box,
} from "@react-three/drei";
import logo from "./logo.svg";
import "./App.css";

const GLTFModel = (props) => {
  const gltf = useGLTF(props.url);
  // console.log(gltf);
  return <primitive {...props} object={gltf.scene} />;
};

const GLTFModel2 = (props) => {
  const { nodes, materials } = useGLTF(props.url);
  // console.log(nodes, materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["BLADE_(1)_(1)_(1)_Steel_-_Satin_0"].geometry}
        material-color="white"
      />
      <mesh geometry={nodes["BLADE_(1)_(1)_Steel_-_Satin_0"].geometry} />
      <mesh geometry={nodes["BLADE_(1)_Steel_-_Satin_0"].geometry} />
      <mesh geometry={nodes["BLADE_Steel_-_Satin_0"].geometry} />
      <mesh
        geometry={nodes["PIPE_(1)_Steel_-_Satin_0"].geometry}
        material-color="#fff"
      />
      <mesh
        geometry={nodes["PIPE_Steel_-_Satin_0"].geometry}
        material-color="#fff"
      />
      <mesh
        geometry={nodes["UNIT_Steel_-_Satin_0"].geometry}
        material-color="#e9e9e9"
      />
    </group>
  );
};

function Model(props) {
  /*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  author: JasperTobias (https://sketchfab.com/JasperTobias)
  license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  source: https://sketchfab.com/3d-models/lowpoly-earth-ce0cce9b528b47c7984bf0b2b600d705
  title: LowPoly Earth
  */

  return (
    <group {...props} dispose={null}>
      <RoundedBox args={[1, 2, 1]} radius={0.05} smoothness={4}>
        <meshPhongMaterial color="#00adef" wireframe />
      </RoundedBox>
      <Box args={[1, 0.3, 1]} position={[0, -0.5, 0]}>
        <meshBasicMaterial color={props.colors[0]} />
      </Box>
      <Box args={[1, 0.3, 1]}>
        <meshBasicMaterial color={props.colors[1]} />
      </Box>
      <Box args={[1, 0.3, 1]} position={[0, 0.5, 0]}>
        <meshBasicMaterial color={props.colors[2]} />
      </Box>
    </group>
  );
}

function App() {
  const ref = useRef();
  return (
    <div className="App">
      <Canvas dpr={[1, 2]} camera={{ position: [5, 0, 0], fov: 50 }}>
        <mesh />
        <Model
          position={[0, 1.3, 0]}
          colors={["#3f3f3f", "#00adef", "green"]}
        />
        <Model
          position={[2, 1.3, 0]}
          colors={["red", "orange", "lightgreen"]}
        />
        <GLTFModel
          position={[4, 1.3, 0]}
          url="/shiba/scene.gltf"
          color="#00adef"
        />
        <GLTFModel2
          position={[0, 3.3, 0]}
          url="/air_conditioner/scene.gltf"
          scale={[0.2, 0.2, 0.2]}
          wireframe
        />
        <gridHelper args={[10, 20]} />
        <OrbitControls ref={ref} />
      </Canvas>
    </div>
  );
}

export default App;
